# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19lqycfqgohmNdJ1xQTm2j_33GCVLLMSb
"""

!pip install numpy pandas matplotlib seaborn scikit-learn

!pip install tensorflow torch torchvision

import torch

print("GPU Available:", torch.cuda.is_available())
print("GPU Name:", torch.cuda.get_device_name(0))

!nvidia-smi

import sys
print(sys.version)

import numpy
import pandas
import matplotlib
import sklearn

print("All libraries imported successfully!")

# Install libraries
!pip install numpy pandas matplotlib seaborn scikit-learn

# Check GPU
!nvidia-smi

# Verify libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

print("Environment setup complete!")

!pip install transformers accelerate huggingface_hub

from huggingface_hub import login

login()

from huggingface_hub import login

login()

from huggingface_hub import login

login()

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_name = "ibm-granite/granite-3.3-2b-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto"
)

prompt = "Explain what artificial intelligence is in simple terms."

inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

outputs = model.generate(**inputs, max_new_tokens=100)

response = tokenizer.decode(outputs[0], skip_special_tokens=True)

print(response)

outputs = model.generate(
    **inputs,
    max_new_tokens=150,
    temperature=0.7,
    top_p=0.9,
    do_sample=True
)

print(tokenizer.decode(outputs[0], skip_special_tokens=True))

outputs = model.generate(
    **inputs,
    max_new_tokens=200,
    temperature=0.7,
    top_p=0.9,
    repetition_penalty=1.1,
    do_sample=True
)

prompt = "Write a short paragraph about cloud computing."

inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

outputs = model.generate(
    **inputs,
    max_new_tokens=120,
    temperature=0.7,
    top_p=0.9,
    do_sample=True
)

print(tokenizer.decode(outputs[0], skip_special_tokens=True))

!pip install gradio

import gradio as gr

print("Gradio installed successfully!")

import gradio as gr

def greet(name):
    return "Hello " + name + "!"

interface = gr.Interface(
    fn=greet,
    inputs="text",
    outputs="text"
)

interface.launch(share=True)

import gradio as gr

def greet(name):
    return "Welcome " + name

demo = gr.Interface(
    fn=greet,
    inputs="text",
    outputs="text",
    title="Simple Gradio App"
)

demo.launch(share=True)

Running on public URL: https://xxxxx.gradio.live

Running on local URL
Running on public URL

# Running on public URL: https://b82b20b561a6b08966.gradio.live

# Running on local URL
# Running on public URL

import gradio as gr

def square_number(num):
    return num * num

app = gr.Interface(
    fn=square_number,
    inputs=gr.Number(label="Enter a Number"),
    outputs=gr.Number(label="Square Result"),
    title="Gradio Test Interface"
)

app.launch(share=True)

import random

# -------------------------------
# Activity 2.1 Color Palette Generator
# -------------------------------

class ColorPaletteGenerator:

    def __init__(self):

        self.palettes = {
            "modern": ["#2C3E50","#3498DB","#ECF0F1","#1ABC9C","#34495E"],
            "dark": ["#121212","#1F1F1F","#BB86FC","#03DAC6","#CF6679"],
            "nature": ["#2E8B57","#3CB371","#F0FFF0","#8FBC8F","#556B2F"],
            "sunset": ["#FF5733","#FF8D1A","#FFC300","#C70039","#900C3F"],
            "pastel": ["#FFD1DC","#C1E1C1","#AEC6CF","FDFD96","#FFB347"],
            "ocean": ["#0077BE","#00A8E8","#90E0EF","CAF0F8","#03045E"],
            "minimal": ["#FFFFFF","#F5F5F5","DDDDDD","#333333","#000000"],
            "neon": ["#39FF14","#FF073A","#04D9FF","#FF00FF","#F5F500"]
        }

    def get_palette(self,name=None):

        if name and name in self.palettes:
            return self.palettes[name]

        return random.choice(list(self.palettes.values()))

    def validate_color(self,color):

        if color.startswith("#") and len(color)==7:
            return True
        return False



# -------------------------------
# Activity 2.3 CSS Generator
# -------------------------------

class CSSGenerator:

    def generate_css(self,palette):

        primary = palette[0]
        secondary = palette[1]
        background = palette[2]

        css = f"""

* {{
margin:0;
padding:0;
box-sizing:border-box;
font-family:Arial;
}}

body {{
background:{background};
color:#333;
}}

header {{
background:{primary};
color:white;
padding:80px;
text-align:center;
}}

button {{
background:{secondary};
color:white;
padding:12px 25px;
border:none;
cursor:pointer;
transition:0.3s;
}}

button:hover {{
transform:scale(1.1);
}}

.features {{
display:grid;
grid-template-columns:repeat(3,1fr);
gap:20px;
padding:40px;
}}

.feature-box {{
background:white;
padding:20px;
border-radius:10px;
box-shadow:0 0 10px rgba(0,0,0,0.1);
}}

.portfolio {{
display:grid;
grid-template-columns:repeat(3,1fr);
gap:15px;
padding:40px;
}}

.portfolio img {{
width:100%;
border-radius:10px;
}}

.contact {{
padding:40px;
text-align:center;
}}

input,textarea {{
width:80%;
padding:10px;
margin:10px;
}}

.pricing {{
display:flex;
gap:20px;
justify-content:center;
padding:40px;
}}

.price-card {{
background:white;
padding:20px;
border-radius:10px;
box-shadow:0 0 10px rgba(0,0,0,0.1);
}}

.testimonials {{
padding:40px;
text-align:center;
}}

footer {{
background:{primary};
color:white;
text-align:center;
padding:20px;
}}

@media (max-width:768px) {{

.features {{
grid-template-columns:1fr;
}}

.portfolio {{
grid-template-columns:1fr;
}}

.pricing {{
flex-direction:column;
}}

}}

"""
        return css



# -------------------------------
# Activity 2.4 Section Templates
# -------------------------------

class SectionTemplates:


    def hero(self):

        return """
<header>
<h1>Welcome to My Website</h1>
<p>Modern website generated automatically</p>
<button>Get Started</button>
</header>
"""


    def features(self):

        return """
<section class="features">

<div class="feature-box">
<h3>Fast</h3>
<p>Lightning fast performance</p>
</div>

<div class="feature-box">
<h3>Responsive</h3>
<p>Mobile friendly design</p>
</div>

<div class="feature-box">
<h3>Secure</h3>
<p>Safe and reliable system</p>
</div>

</section>
"""


    def about(self):

        return """
<section class="about">
<h2>About Me</h2>
<p>I am a freelance designer with a passion for creating beautiful and functional websites. With years of experience, I specialize in responsive design and user-centric interfaces, helping clients bring their visions to life.</p>
</section>
"""


    def portfolio(self):

        return """
<section class="portfolio">

<img src="https://picsum.photos/300/200?1">
<img src="https://picsum.photos/300/200?2">
<img src="https://picsum.photos/300/200?3">

</section>
"""


    def contact(self):

        return """
<section class="contact">

<h2>Contact Us</h2>

<input type="text" placeholder="Name"><br>
<input type="email" placeholder="Email"><br>

<textarea placeholder="Message"></textarea><br>

<button>Send</button>

</section>
"""


    def pricing(self):

        return """
<section class="pricing">

<div class="price-card">
<h3>Basic</h3>
<p>$10/month</p>
</div>

<div class="price-card">
<h3>Pro</h3>
<p>$25/month</p>
</div>

<div class="price-card">
<h3>Enterprise</h3>
<p>$50/month</p>
</div>

</section>
"""


    def testimonials(self):

        return """
<section class="testimonials">

<h2>Testimonials</h2>

<p>"Amazing service!"</p>
<p>"Highly recommended"</p>

</section>
"""



# -------------------------------
# Activity 2.2 HTML Page Builder
# -------------------------------

class HTMLPageBuilder:

    def generate_seo(self,title):

        return f"""
<title>{title}</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<meta name="description" content="Generated website">
"""


    def build_page(self,sections,css):

        html = f"""
<!DOCTYPE html>
<html>

<head>

{self.generate_seo("Auto Website")}

<style>
{css}
</style>

</head>

<body>

{sections}

<footer>
<p>© 2026 My Website</p>
<div class="social-links">
    <a href="#" target="_blank">Facebook</a>
    <a href="#" target="_blank">Twitter</a>
    <a href="#" target="_blank">LinkedIn</a>
</div>
<p>Email: info@mywebsite.com | Phone: 555-123-4567</p>
</footer>

</body>
</html>
"""

        return html



# -------------------------------
# MAIN PROGRAM
# -------------------------------

paletteGen = ColorPaletteGenerator()

palette = paletteGen.get_palette()

cssGen = CSSGenerator()
css = cssGen.generate_css(palette)

templates = SectionTemplates()

sections = (
templates.hero() +
templates.features() +
templates.about() +  # Added the new about section
templates.portfolio() +
templates.pricing() +
templates.testimonials() +
templates.contact()
)

builder = HTMLPageBuilder()

html = builder.build_page(sections,css)

file = open("generated_site.html","w",encoding="utf-8")
file.write(html)
file.close()

print("Portfolio Website Generated Successfully!")

pip install gradio

pip install gradio

import gradio as gr

def display_website():
    with open('generated_site.html', 'r', encoding='utf-8') as f:
        html_content = f.read()
    return html_content

website_interface = gr.Interface(
    fn=display_website,
    inputs=None,
    outputs=gr.HTML(label='Generated Website'),
    title='Generated Portfolio Website',
    live=False
)

website_interface.launch(share=True)

!pip install gradio

import gradio as gr

def generate_html(title, theme):

    html = f"""
    <html>
    <head>
    <title>{title}</title>
    </head>
    <body style="background-color:{theme};">
    <h1>Welcome to {title}</h1>
    <p>This website is generated automatically.</p>
    </body>
    </html>
    """

    return html, html

with gr.Blocks() as demo:

    with gr.Tabs():

        with gr.Tab("Website Input"):
            title = gr.Textbox(label="Website Title")
            theme = gr.Dropdown(["white","lightblue","lightgray"], label="Theme")
            btn = gr.Button("Generate Website")

        with gr.Tab("HTML Code"):
            html_code = gr.Code(label="Generated HTML")

        with gr.Tab("Live Preview"):
            preview = gr.HTML()

    btn.click(generate_html, inputs=[title,theme], outputs=[html_code,preview])

demo.launch()

# -*- coding: utf-8 -*-
"""granite-3.3-2b-instruct.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//huggingface.co/ibm-granite/granite-3.3-2b-instruct.ipynb
"""

!pip install -U transformers

"""## Local Inference on GPU
Model page: https://huggingface.co/ibm-granite/granite-3.3-2b-instruct

⚠️ If the generated code snippets do not work, please open an issue on either the [model repo](https://huggingface.co/ibm-granite/granite-3.3-2b-instruct)
			and/or on [huggingface.js](https://github.com/huggingface/huggingface.js/blob/main/packages/tasks/src/model-libraries-snippets.ts) 🙏
"""

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-generation", model="ibm-granite/granite-3.3-2b-instruct")
messages = [
    {"role": "user", "content": "Who are you?"},
]
pipe(messages)

# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
model = AutoModelForCausalLM.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
messages = [
    {"role": "user", "content": "Who are you?"},
]
inputs = tokenizer.apply_chat_template(
	messages,
	add_generation_prompt=True,
	tokenize=True,
	return_dict=True,
	return_tensors="pt",
).to(model.device)

outputs = model.generate(**inputs, max_new_tokens=40)
print(tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:]))

!pip install -q gradio

import gradio as gr
import json
import re
from datetime import datetime
from typing import Tuple, Dict, List
import random

# ============================================================================
# HTML QUICK-STYLER - ADVANCED VERSION (FIXED)
# ============================================================================

class ColorPaletteGenerator:
    """Generate visually cohesive color palettes"""

    @staticmethod
    def generate_palette(style: str = "modern") -> Dict[str, str]:
        """Generate a cohesive color palette based on style"""

        palettes = {
            'modern': {
                'primary': '#667eea',
                'secondary': '#764ba2',
                'accent': '#f093fb',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'vibrant': {
                'primary': '#ff6b6b',
                'secondary': '#ff8e72',
                'accent': '#f5576c',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'ocean': {
                'primary': '#0099cc',
                'secondary': '#006699',
                'accent': '#00ccff',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'forest': {
                'primary': '#27ae60',
                'secondary': '#1e8449',
                'accent': '#52be80',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'sunset': {
                'primary': '#ff8c42',
                'secondary': '#ff6b35',
                'accent': '#ffa751',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'luxury': {
                'primary': '#1a1a1a',
                'secondary': '#333333',
                'accent': '#FFD700',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'creative': {
                'primary': '#9b59b6',
                'secondary': '#8e44ad',
                'accent': '#e74c3c',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'minimal': {
                'primary': '#2c3e50',
                'secondary': '#34495e',
                'accent': '#3498db',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            }
        }

        return palettes.get(style.lower(), palettes['modern'])

class HTMLPageBuilder:
    """Build styled HTML pages from descriptions"""

    @staticmethod
    def extract_sections(description: str) -> List[str]:
        """Extract sections from description"""
        sections = []

        section_keywords = {
            'hero': ['hero', 'banner', 'landing'],
            'features': ['features', 'services', 'benefits'],
            'about': ['about', 'team', 'company'],
            'portfolio': ['portfolio', 'gallery', 'work', 'projects'],
            'testimonials': ['testimonial', 'reviews', 'feedback'],
            'pricing': ['pricing', 'plans', 'cost'],
            'contact': ['contact', 'form', 'reach'],
            'footer': ['footer', 'bottom']
        }

        desc_lower = description.lower()

        for section_type, keywords in section_keywords.items():
            for keyword in keywords:
                if keyword in desc_lower:
                    sections.append(section_type)
                    break

        if not sections:
            sections = ['hero', 'features', 'contact', 'footer']

        return sections

    @staticmethod
    def generate_meta_tags(title: str, description: str) -> str:
        """Generate SEO meta tags"""
        meta_tags = f'''    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <meta name="description" content="{description[:160]}">
    <meta name="theme-color" content="#0f172a">
    <meta property="og:title" content="{title}">
    <meta property="og:description" content="{description[:160]}">
    <meta property="og:type" content="website">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="author" content="HTML Quick-Styler">'''
        return meta_tags

    @staticmethod
    def generate_section_html(section_type: str, palette: Dict) -> str:
        """Generate HTML for specific section"""
        sections = {
            'hero': f'''        <section class="hero">
            <div class="hero-content">
                <h1>Welcome to Your Site</h1>
                <p>Create amazing web experiences</p>
                <button class="btn btn-primary">Get Started</button>
            </div>
        </section>''',

            'features': f'''        <section class="features">
            <h2>Features</h2>
            <div class="features-grid">
                <div class="feature-card">
                    <h3>Fast</h3>
                    <p>Lightning-quick performance</p>
                </div>
                <div class="feature-card">
                    <h3>Secure</h3>
                    <p>Enterprise-grade security</p>
                </div>
                <div class="feature-card">
                    <h3>Scalable</h3>
                    <p>Grow without limits</p>
                </div>
            </div>
        </section>''',

            'about': f'''        <section class="about">
            <div class="about-content">
                <h2>About Us</h2>
                <p>We're passionate about creating beautiful, functional websites that help your business grow.</p>
            </div>
        </section>''',

            'portfolio': f'''        <section class="portfolio">
            <h2>Our Work</h2>
            <div class="portfolio-grid">
                <div class="portfolio-item"></div>
                <div class="portfolio-item"></div>
                <div class="portfolio-item"></div>
            </div>
        </section>''',

            'testimonials': f'''        <section class="testimonials">
            <h2>What People Say</h2>
            <div class="testimonials-grid">
                <div class="testimonial">
                    <p>"Amazing service!"</p>
                    <span>- Client Name</span>
                </div>
                <div class="testimonial">
                    <p>"Highly recommended!"</p>
                    <span>- Happy Customer</span>
                </div>
            </div>
        </section>''',

            'pricing': f'''        <section class="pricing">
            <h2>Pricing Plans</h2>
            <div class="pricing-grid">
                <div class="pricing-card">
                    <h3>Starter</h3>
                    <p class="price">$29</p>
                    <ul><li>Feature 1</li><li>Feature 2</li></ul>
                </div>
                <div class="pricing-card featured">
                    <h3>Pro</h3>
                    <p class="price">$79</p>
                    <ul><li>All Starter</li><li>Feature 3</li></ul>
                </div>
            </div>
        </section>''',

            'contact': f'''        <section class="contact">
            <h2>Get in Touch</h2>
            <form class="contact-form">
                <input type="text" placeholder="Your Name" required>
                <input type="email" placeholder="Your Email" required>
                <textarea placeholder="Your Message" rows="5" required></textarea>
                <button type="submit" class="btn btn-primary">Send Message</button>
            </form>
        </section>''',

            'footer': f'''        <footer class="footer">
            <div class="footer-content">
                <p>&copy; 2024 Your Company. All rights reserved.</p>
                <div class="footer-links">
                    <a href="#privacy">Privacy</a>
                    <a href="#terms">Terms</a>
                    <a href="#contact">Contact</a>
                </div>
            </div>
        </footer>'''
        }

        return sections.get(section_type, '')

    @staticmethod
    def generate_css(palette: Dict) -> str:
        """Generate comprehensive CSS"""
        css = f'''    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}

        :root {{
            --primary: {palette['primary']};
            --secondary: {palette['secondary']};
            --accent: {palette['accent']};
            --background: {palette['background']};
            --surface: {palette['surface']};
            --text-primary: {palette['text_primary']};
            --text-secondary: {palette['text_secondary']};
            --border: {palette['border']};
        }}

        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, var(--background) 0%, var(--surface) 100%);
            color: var(--text-primary);
            line-height: 1.6;
            min-height: 100vh;
        }}

        header {{
            background: rgba(15, 23, 42, 0.95);
            backdrop-filter: blur(10px);
            padding: 1.5rem 2rem;
            position: sticky;
            top: 0;
            z-index: 100;
            border-bottom: 1px solid var(--border);
        }}

        header nav {{
            display: flex;
            justify-content: space-between;
            align-items: center;
            max-width: 1200px;
            margin: 0 auto;
        }}

        header h1 {{
            font-size: 1.8rem;
            background: linear-gradient(135deg, var(--primary), var(--accent));
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
        }}

        header nav a {{
            color: var(--text-secondary);
            text-decoration: none;
            margin: 0 1.5rem;
            transition: color 0.3s ease;
        }}

        header nav a:hover {{
            color: var(--primary);
        }}

        main {{
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 2rem;
        }}

        section {{
            padding: 4rem 0;
            animation: fadeIn 0.6s ease-in;
        }}

        @keyframes fadeIn {{
            from {{
                opacity: 0;
                transform: translateY(20px);
            }}
            to {{
                opacity: 1;
                transform: translateY(0);
            }}
        }}

        h1, h2, h3 {{
            color: var(--text-primary);
            margin-bottom: 1rem;
        }}

        h1 {{
            font-size: 3rem;
            font-weight: 700;
        }}

        h2 {{
            font-size: 2rem;
            margin-bottom: 2rem;
            text-align: center;
        }}

        h3 {{
            font-size: 1.3rem;
        }}

        .hero {{
            background: linear-gradient(135deg, var(--primary) 0%, var(--secondary) 100%);
            color: white;
            padding: 6rem 0;
            text-align: center;
            min-height: 500px;
            display: flex;
            align-items: center;
            justify-content: center;
        }}

        .hero h1 {{
            color: white;
            font-size: 4rem;
            margin-bottom: 1rem;
            animation: slideDown 0.8s ease;
        }}

        .hero p {{
            font-size: 1.5rem;
            margin-bottom: 2rem;
            opacity: 0.95;
            animation: slideUp 0.8s ease;
        }}

        @keyframes slideDown {{
            from {{
                opacity: 0;
                transform: translateY(-30px);
            }}
            to {{
                opacity: 1;
                transform: translateY(0);
            }}
        }}

        @keyframes slideUp {{
            from {{
                opacity: 0;
                transform: translateY(30px);
            }}
            to {{
                opacity: 1;
                transform: translateY(0);
            }}
        }}

        .btn {{
            padding: 0.8rem 2rem;
            border: none;
            border-radius: 8px;
            font-size: 1rem;
            cursor: pointer;
            transition: all 0.3s ease;
            font-weight: 600;
        }}

        .btn-primary {{
            background: var(--primary);
            color: white;
            box-shadow: 0 4px 15px rgba(0,0,0,0.3);
        }}

        .btn-primary:hover {{
            transform: translateY(-2px);
            box-shadow: 0 6px 20px rgba(0,0,0,0.4);
            background: var(--accent);
        }}

        .btn-secondary {{
            background: var(--secondary);
            color: white;
        }}

        .btn-secondary:hover {{
            background: var(--primary);
        }}

        .features-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 2rem;
        }}

        .feature-card {{
            background: rgba(30, 41, 59, 0.8);
            padding: 2rem;
            border-radius: 12px;
            border: 1px solid var(--border);
            transition: all 0.3s ease;
            backdrop-filter: blur(10px);
        }}

        .feature-card:hover {{
            transform: translateY(-8px);
            border-color: var(--primary);
            box-shadow: 0 20px 40px rgba(0,0,0,0.3);
        }}

        .feature-card h3 {{
            color: var(--primary);
            margin-bottom: 0.5rem;
        }}

        .feature-card p {{
            color: var(--text-secondary);
        }}

        .portfolio-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
            gap: 2rem;
        }}

        .portfolio-item {{
            aspect-ratio: 1;
            background: linear-gradient(135deg, var(--primary), var(--secondary));
            border-radius: 12px;
            cursor: pointer;
            transition: all 0.3s ease;
            border: 1px solid var(--border);
        }}

        .portfolio-item:hover {{
            transform: scale(1.05);
            box-shadow: 0 20px 40px rgba(0,0,0,0.3);
        }}

        .about {{
            text-align: center;
        }}

        .about-content {{
            max-width: 800px;
            margin: 0 auto;
        }}

        .about p {{
            font-size: 1.1rem;
            color: var(--text-secondary);
        }}

        .testimonials-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 2rem;
        }}

        .testimonial {{
            background: rgba(30, 41, 59, 0.8);
            padding: 2rem;
            border-left: 4px solid var(--primary);
            border-radius: 8px;
        }}

        .testimonial p {{
            font-style: italic;
            margin-bottom: 1rem;
            color: var(--text-secondary);
        }}

        .testimonial span {{
            font-weight: 600;
            color: var(--primary);
        }}

        .pricing-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 2rem;
        }}

        .pricing-card {{
            background: rgba(30, 41, 59, 0.8);
            padding: 2rem;
            border-radius: 12px;
            border: 1px solid var(--border);
            text-align: center;
            transition: all 0.3s ease;
        }}

        .pricing-card.featured {{
            border-color: var(--primary);
            box-shadow: 0 20px 40px rgba(0,0,0,0.3);
            transform: scale(1.05);
        }}

        .pricing-card .price {{
            font-size: 2.5rem;
            color: var(--primary);
            margin: 1rem 0;
            font-weight: 700;
        }}

        .pricing-card ul {{
            list-style: none;
            margin: 1.5rem 0;
            text-align: left;
        }}

        .pricing-card li {{
            padding: 0.5rem 0;
            color: var(--text-secondary);
        }}

        .contact {{
            max-width: 600px;
            margin: 0 auto;
        }}

        .contact-form {{
            display: flex;
            flex-direction: column;
            gap: 1.5rem;
        }}

        .contact-form input,
        .contact-form textarea {{
            padding: 1rem;
            border: 1px solid var(--border);
            border-radius: 8px;
            background: rgba(30, 41, 59, 0.8);
            color: var(--text-primary);
            font-family: inherit;
            font-size: 1rem;
        }}

        .contact-form input:focus,
        .contact-form textarea:focus {{
            outline: none;
            border-color: var(--primary);
            box-shadow: 0 0 0 3px rgba(0,0,0,0.3);
        }}

        .footer {{
            background: rgba(15, 23, 42, 0.95);
            border-top: 1px solid var(--border);
            margin-top: 4rem;
            padding: 3rem 0;
        }}

        .footer-content {{
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 2rem;
            display: flex;
            justify-content: space-between;
            align-items: center;
            flex-wrap: wrap;
            gap: 2rem;
        }}

        .footer-links {{
            display: flex;
            gap: 2rem;
        }}

        .footer-links a {{
            color: var(--text-secondary);
            text-decoration: none;
            transition: color 0.3s ease;
        }}

        .footer-links a:hover {{
            color: var(--primary);
        }}

        @media (max-width: 768px) {{
            header nav {{
                flex-direction: column;
                gap: 1rem;
            }}

            header h1 {{
                font-size: 1.4rem;
            }}

            .hero h1 {{
                font-size: 2rem;
            }}

            .hero p {{
                font-size: 1.1rem;
            }}

            h2 {{
                font-size: 1.5rem;
            }}

            main {{
                padding: 0 1rem;
            }}

            section {{
                padding: 2rem 0;
            }}

            .footer-content {{
                flex-direction: column;
                text-align: center;
            }}
        }}
    </style>'''
        return css

class HTMLGenerationEngine:
    """Main engine for HTML page generation"""

    @staticmethod
    def generate_page(title: str, description: str, style: str = "modern") -> Tuple[str, str]:
        """Generate complete HTML page"""

        # Generate color palette
        palette = ColorPaletteGenerator.generate_palette(style)

        # Extract sections
        sections = HTMLPageBuilder.extract_sections(description)

        # Generate meta tags
        meta_tags = HTMLPageBuilder.generate_meta_tags(title, description)

        # Generate sections
        sections_html = '\n\n'.join([
            HTMLPageBuilder.generate_section_html(section, palette)
            for section in sections
            if HTMLPageBuilder.generate_section_html(section, palette)
        ])

        # Generate CSS
        css = HTMLPageBuilder.generate_css(palette)

        # Build complete HTML
        html = f'''<!DOCTYPE html>
<html lang="en">
<head>
{meta_tags}
{css}
</head>
<body>
    <header>
        <nav>
            <h1>{title}</h1>
            <div>
                <a href="#features">Features</a>
                <a href="#about">About</a>
                <a href="#contact">Contact</a>
            </div>
        </nav>
    </header>

    <main>
{sections_html}
    </main>
</body>
</html>'''

        return html, palette

generation_history = []

def generate_html_page(title: str, description: str, style: str = "modern") -> Tuple[str, str, str]:
    """Generate HTML page with styling"""
    if not title.strip() or not description.strip():
        return "", "❌ Please provide both title and description!", ""

    try:
        html_output, palette = HTMLGenerationEngine.generate_page(title, description, style)

        color_info = f"""
**Color Palette:**
- Primary: {palette['primary']}
- Secondary: {palette['secondary']}
- Accent: {palette['accent']}
- Background: {palette['background']}
"""

        generation_history.append({
            'title': title,
            'description': description,
            'html': html_output,
            'palette': palette,
            'timestamp': datetime.now().isoformat()
        })

        return html_output, "✅ HTML page generated successfully!", color_info
    except Exception as e:
        return "", f"❌ Error: {str(e)}", ""

def get_color_suggestions(style: str) -> str:
    """Get color suggestions based on style"""
    palette = ColorPaletteGenerator.generate_palette(style)

    palette_text = f"""
**Palette for "{style}" style:**
- Primary: {palette['primary']}
- Secondary: {palette['secondary']}
- Accent: {palette['accent']}
- Background: {palette['background']}
- Text: {palette['text_primary']}
"""
    return palette_text

print("🚀 Loading HTML Quick-Styler Advanced...")

with gr.Blocks(title="HTML Quick-Styler - Advanced Edition") as demo:

    gr.Markdown("""
    # 🎨 HTML Quick-Styler Advanced
    ## Professional HTML Page Generator with Auto-Styling

    **Generate production-ready HTML pages in seconds**
    """)

    with gr.Tabs():

        # ============= TAB 1: Page Generator =============
        with gr.TabItem("🎯 Generate Page"):
            with gr.Row():
                with gr.Column(scale=1):
                    gr.Markdown("### 📝 Page Details")

                    page_title = gr.Textbox(
                        label="Page Title",
                        value="Modern Portfolio Website",
                        lines=1
                    )

                    page_description = gr.Textbox(
                        label="Page Description & Sections",
                        value="Hero section with welcome message, features list with 3 items, about section, portfolio gallery, testimonials, contact form, and footer",
                        lines=4
                    )

                    color_style = gr.Dropdown(
                        ["modern", "vibrant", "ocean", "forest", "sunset", "luxury", "creative", "minimal"],
                        value="modern",
                        label="🎨 Color Style"
                    )

                    generate_btn = gr.Button("✨ Generate HTML", size="lg", variant="primary")

                with gr.Column(scale=1):
                    gr.Markdown("### 📊 Output")

                    html_output = gr.Code(
                        language="html",
                        label="Generated HTML/CSS",
                        lines=20
                    )

                    status_msg = gr.Markdown()
                    color_info = gr.Markdown()

            generate_btn.click(
                generate_html_page,
                inputs=[page_title, page_description, color_style],
                outputs=[html_output, status_msg, color_info]
            )

        # ============= TAB 2: Preview =============
        with gr.TabItem("👁️ Live Preview"):
            gr.Markdown("### 🔍 Preview Generated Page")

            preview_button = gr.Button("🔄 Load Preview", size="lg", variant="primary")
            preview_output = gr.HTML(value="<p style='text-align:center; color:#fff; padding:40px;'>No preview loaded. Generate a page first.</p>")

            def show_preview(html_text):
                if not html_text.strip():
                    return "<p style='text-align:center; color:#fff; padding:40px;'>No HTML provided</p>"
                return html_text

            preview_button.click(
                show_preview,
                inputs=[html_output],
                outputs=[preview_output]
            )

        # ============= TAB 3: Color Palettes =============
        with gr.TabItem("🎨 Color Palettes"):
            gr.Markdown("### 🌈 Explore Color Schemes")

            with gr.Row():
                style_selector = gr.Radio(
                    ["modern", "vibrant", "ocean", "forest", "sunset", "luxury", "creative", "minimal"],
                    value="modern",
                    label="Choose Style"
                )

                palette_btn = gr.Button("🎨 Get Palette", size="lg", variant="primary")

            palette_display = gr.Markdown()

            palette_btn.click(
                get_color_suggestions,
                inputs=[style_selector],
                outputs=[palette_display]
            )

        # ============= TAB 4: Templates =============
        with gr.TabItem("📋 Templates"):
            gr.Markdown("### 📝 Quick Templates")

            with gr.Row():
                with gr.Column():
                    gr.Markdown("""
                    #### Portfolio Website
                    Hero, Portfolio Gallery, About, Contact, Footer
                    """)
                    portfolio_btn = gr.Button("Use Template", size="sm")

                    def load_portfolio():
                        return ("Portfolio Website",
                               "Hero section with welcome banner, portfolio gallery with 6 items, about section, testimonials, contact form, footer",
                               "modern")

                    portfolio_btn.click(load_portfolio, outputs=[page_title, page_description, color_style])

                with gr.Column():
                    gr.Markdown("""
                    #### SaaS Landing Page
                    Hero, Features, Pricing, Testimonials, CTA, Footer
                    """)
                    saas_btn = gr.Button("Use Template", size="sm")

                    def load_saas():
                        return ("SaaS Product",
                               "Hero banner, features showcase with 3 items, pricing plans comparison, testimonials, call-to-action button, footer",
                               "vibrant")

                    saas_btn.click(load_saas, outputs=[page_title, page_description, color_style])

                with gr.Column():
                    gr.Markdown("""
                    #### Company Website
                    Header, About, Services, Team, Contact, Footer
                    """)
                    company_btn = gr.Button("Use Template", size="sm")

                    def load_company():
                        return ("Company",
                               "Header with navigation, hero section, about company, services list, team members, contact form, footer",
                               "ocean")

                    company_btn.click(load_company, outputs=[page_title, page_description, color_style])

        # ============= TAB 5: Guide =============
        with gr.TabItem("📚 Guide"):
            gr.Markdown("""
            # 📖 HTML Quick-Styler Guide

            ## How It Works

            ### 1. Enter Details
            - **Title:** Page name
            - **Description:** Sections you want
            - **Color Style:** Pick a theme

            ### 2. Automatic Detection
            The tool recognizes these keywords:
            - `hero` / `banner` → Hero Section
            - `features` / `services` → Features Grid
            - `about` / `team` → About Section
            - `portfolio` / `gallery` → Portfolio
            - `testimonial` / `reviews` → Testimonials
            - `pricing` / `plans` → Pricing Plans
            - `contact` / `form` → Contact Form
            - `footer` → Footer

            ### 3. Generate & Customize
            - Copy generated HTML
            - Edit text and colors
            - Save as .html file
            - Open in browser

            ## Features
            ✅ Responsive design
            ✅ Modern animations
            ✅ SEO meta tags
            ✅ Professional styling
            ✅ Dark theme
            ✅ Color palettes
            ✅ Copy-paste ready

            ## Color Styles
            - **Modern:** Professional blues
            - **Vibrant:** Bold reds
            - **Ocean:** Calm blues
            - **Forest:** Natural greens
            - **Sunset:** Warm oranges
            - **Luxury:** Elegant blacks
            - **Creative:** Purple artistic
            - **Minimal:** Clean grays
            """)

print("\n✅ HTML Quick-Styler Advanced Ready!\n")
demo.launch(share=True, show_error=True, show_api=False)